apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: fruits-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
        envFrom:
          - secretRef:
              name: "db-mongo-secrets"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
