apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-secret
  namespace: fruits-app 
spec:
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: "db-mongo-secrets"
    creationPolicy: Owner
  dataFrom:
  - extract: 
      key: {{ .Values.global.secretName }}
        
   